resources:
  - name: droDocWebhook
    type: IncomingWebhook
    configuration:
      webhookName: triggerDroBundle
  
pipelines:
  - name: dro_create_bundle
    configuration:
      chronological: true
    steps:
    - name: ExtractFileName
      type: Bash
      configuration:
        inputResources:
          - name: droDocWebhook

      execution:
          onExecute:
            - echo "TODO !"
            
